# Generated by Django 5.2.12 on 2026-03-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_clinicianprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("CLINICIAN", "Clinician"),
                    ("ADMIN", "Admin"),
                ],
                default="PATIENT",
                max_length=20,
            ),
        ),
    ]
