# Generated by Django 5.2.12 on 2026-04-02 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_message_sender_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="PressureFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                ("data", models.JSONField()),
                ("source_filename", models.CharField(blank=True, max_length=200)),
                ("frame_index", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pressure_frames",
                        to="core.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "frame_index"],
            },
        ),
    ]
